version: '3.1'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./hanamimusic.cn_nginx:/etc/nginx/ssl:ro
    depends_on:
      - wordpress

  wordpress:
    image: wordpress
    restart: always
    expose:
      - "80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: hanami
      WORDPRESS_DB_PASSWORD: hanami
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: hanami
      MYSQL_PASSWORD: hanami
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: